# Generated by Django 4.1.9 on 2023-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.TextField(default=""),
        ),
    ]
