# Generated by Django 4.1.9 on 2023-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.BinaryField(default=b""),
        ),
        migrations.AlterField(
            model_name="user",
            name="metadata",
            field=models.BinaryField(default=b""),
        ),
    ]
